[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rug_pull_chronicles_program = "6cfjRrqry3MFPH9L7r2A44iCnCuoin6dauAwv1xa1Sc9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "target/deploy/mpl_core.so"

# [toolchain]

# [features]
# resolution = true
# skip-lint = false

# [programs.localnet]
# metaplex_core_example = "AisPtd8Pkci6V6x38MeZHBd5i7riJU8jCuHKtLLThCNM"

# [registry]
# url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

# [scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [[test.genesis]]
# address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
# program = "target/deploy/mpl_core.so"

